### PR TITLE
enh(CPlusPlus): bubble-sort

### PR DESCRIPTION
**Pull request by Ashborn-SM**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] New algorithm
- [x] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

Optimize the bubble-sort algorithm
**Other information:**

### CODE REVIEW

**Comment by ming-tsai** [comment]
Hi @Roshaen,
Could you help me to check this change?

**Comment by Roshaen** [comment]
@ming-tsai 
Sure

**Review by Roshaen — APPROVED** [review]
Well simplified,
Now no need to traverse the array if it is already sorted

**Review by ming-tsai — APPROVED** [review]

**Comment by Ashborn-SM** [comment]
So i have a question about the pull request,
when i create a pull request for this change in bubble sort, my previous commit that was already merged was also part of this request you can look at my commits, why is that?
If i use revert i lose my commit.
Is there a better way to do than git revert?. 

@ming-tsai and @Roshaen could you two help me on this?

**Comment by ming-tsai** [comment]
> So i have a question about the pull request,
> when i create a pull request for this change in bubble sort, my previous commit that was already merged was also part of this request you can look at my commits, why is that?
> If i use revert i lose my commit.
> Is there a better way to do than git revert?. 
> 
> @ming-tsai and @Roshaen could you two help me on this?

If you want to revert only one file you could use `git checkout <!commitId> <!filePath>`

**Pull request merged**
