### PR TITLE
Migrate C++ codes to new directory structure

### PR DESCRIPTION
**Pull request by Arsenic-ATG**
Changes include :- 

- Moving all cpp codes to ~~`/Algorithms/C++`~~ `/Algorithms/CPlusPlus`
- Create and fill index readme file.
- Remove useless codes that were accidentally merged in PR #200 

( reference issue #219 )

### CODE REVIEW

**Review by ming-tsai — CHANGES_REQUESTED** [review]
Could you create a readme file for cop index?

**Comment by Arsenic-ATG** [comment]
> Could you create a readme file for cop index?

assuming that's `cpp index`. Isn't that already existing in the changes ? 

https://github.com/Arsenic-ATG/DSA/blob/cpp_patch/algorithms/C%2B%2B/README.md

or do you want a different one, or maybe I misunderstood anything ?

**Comment by ming-tsai** [comment]
Could you rename rename file name to CPlusPlus?

**Review by ming-tsai — APPROVED** [review]
Nice work

**Pull request merged**
