### PR TITLE
enh(Go): binary-search

### PR DESCRIPTION
**Pull request by ghost**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] New algorithm
- [x] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

Updated binary search to test go workflow.

### CODE REVIEW

**Comment by ming-tsai** [comment]
Hi @atin,
Please solve the [recomendations](https://github.com/MakeContributions/DSA/actions/runs/790080627)

**Comment by atin** [comment]
I have an exam tomorrow so will fix these after that. Hope that's ok!

**Comment by ming-tsai** [comment]
Hi @atin,
Any update with this PR?

**Comment by atin** [comment]
Hey, sorry for not replying early. I've been a little busy with my college work and some other projects recently. Also I think there is some problem with the golangci-lint action, so I'll try to fix that. But right now I can't work on this. So maybe we should close this PR, I'll create a new one sometime later. Once again sorry!

**Comment by ming-tsai** [comment]
Ok, I added invalid label

**Comment by ming-tsai** [comment]
Hi @atin,
I will merge this one, when you have time, help me to check the go-lint warning

**Review by ming-tsai — APPROVED** [review]

**Pull request merged**
