### PR TITLE
chore(Python): add dictionary

### PR DESCRIPTION
**Pull request by hashfx**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [x] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [x] Documentation
- [x] Added "Data Structure in Python" Directory

**Briefly describe the changes in this PR**

**Other information:**

### CODE REVIEW

**Comment by hashfx** [comment]
## Kindly Merge this PR to the main/appropriate branch.
## I have to add more files of data structure namely [ graph, hashtable, LinkedList, list, maxheap, queue, sets, stack, tree, tuple ].

**Review by Arsenic-ATG — COMMENTED** [review]
Sorry but the repo is more focussed on user defined data structures to make one understand how things work behind the scenes rather than how to use them.

**Comment by ming-tsai** [comment]
> Sorry but the repo is more focussed on user defined data structures to make one understand how things work behind the scenes rather than how to use them.

So this will be closed @Arsenic-ATG?

**Comment by Arsenic-ATG** [comment]
> > Sorry but the repo is more focussed on user defined data structures to make one understand how things work behind the scenes rather than how to use them.
> 
> So this will be closed @Arsenic-ATG?

According to me, yes.

**Pull request closed without merging**
