### PR TITLE
chore(Python): add  remove duplicate and first non-repeating character string

### PR DESCRIPTION
**Pull request by Sankalp7943**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**
Added two new strings based algorithms/solutions for Python.

Algorithm 1: Remove Duplicates from a string (using 26character string instead of set/dictionaries)
Algorithm 2: First non repeating character in a string (without using dictionary)

**Other information:**
Updated the readme accordingly.

### CODE REVIEW

**Comment by ming-tsai** [comment]
Hi @Sankalp7943,
Please fix the pull request comment, see [markdown guide](https://www.markdownguide.org/extended-syntax/#task-lists) as example

**Comment by Sankalp7943** [comment]
> Hi @Sankalp7943,
> Please fix the pull request comment, see [markdown guide](https://www.markdownguide.org/extended-syntax/#task-lists) as example

Does it look better?

**Review by Arsenic-ATG — CHANGES_REQUESTED** [review]
program fails if the test string contains anything apart from lower case english alphabets.

**Comment by Sankalp7943** [comment]
> program fails if the test string contains anything apart from lower case english alphabets.

Oh yes, I forgot to add the constraint in the second file. I will fix it .

**Comment by Arsenic-ATG** [comment]
Instead of putting comments telling constraints, it's better to handle them inside your code so that it shows error message instead of straight up crashing in case of invalid input.

**Comment by Sankalp7943** [comment]
> Instead of putting comments telling constraints, it's better to handle them inside your code so that it shows error message instead of straight up crashing in case of invalid input.

Done. Didn't raise error. Just returned Invalid string

**Review by Arsenic-ATG — APPROVED** [review]

**Pull request merged**
