### PR TITLE
Kadane’s Algorithm

### PR DESCRIPTION
**Pull request by aayushjain7**

### CODE REVIEW

**Review by TawfikYasser — CHANGES_REQUESTED** [review]
Hi @aayushjain7 , Welcome to DSA

Please add the program to the appropriate REAMDE file

See our [CONTRIBUTING RULES](https://github.com/MakeContributions/DSA/blob/main/CONTRIBUTING.md)

**Comment by aayushjain7** [comment]
I have added the program to the appropriate REAMDE file.

**Comment by TawfikYasser** [comment]
> I have added the program to the appropriate REAMDE file.

You do not need to open a new Pull Request just update in the current

**Review by TawfikYasser — CHANGES_REQUESTED** [review]
Update in the current PR

**Comment by TawfikYasser** [comment]
Why you closed the PR ? @aayushjain7

**Comment by TawfikYasser** [comment]
Reopen please

**Pull request closed without merging**
