### PR TITLE
chore(Python): add comb_sort

### PR DESCRIPTION
**Pull request by MHRiday**

### CODE REVIEW

**Review by atin — CHANGES_REQUESTED** [review]
@MHRiday you should add a little info about the algorithm like time complexity, algorithm type etc, the rest looks good.

**Comment by ming-tsai** [comment]
Hi @MHRiday,
Are you active?

**Comment by MHRiday** [comment]
@atin I have made some changes. But it is showing I want to merge 4 commits.  Can you help me?

**Comment by MHRiday** [comment]
@ming-tsai I'm active. Sorry for late.

**Review by atin — APPROVED** [review]
Looks good!

**Comment by ming-tsai** [comment]
Hi @MHRiday,
Thanks for contribution and welcome to our team
> The invitation [link](https://github.com/MakeContributions)

**Pull request merged**
