### PR TITLE
Add Python doctests to doubly linked list

### PR DESCRIPTION
**Pull request by cclauss**
% `pytest --doctest-modules .`
```
============================= test session starts ==============================
platform linux -- Python 3.9.4, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: /home/runner/work/DSA/DSA
collected 13 items

arrays/python/count-inversions.py .                                      [  7%]
linked-lists/Python/doubly.py ...                                        [ 30%]
multiplication/python/karatsuba.py ....                                  [ 61%]
scheduling/python/interval-scheduling.py .                               [ 69%]
sorting/python/bubble-sort.py .                                          [ 76%]
sorting/python/insertion-sort.py .                                       [ 84%]
sorting/python/quick-sort.py .                                           [ 92%]
sorting/python/selection-sort.py .                                       [100%]

============================== 13 passed in 0.09s ==============================
```

### CODE REVIEW

**Comment by ming-tsai** [comment]
Hi @cclauss,
Nice work, could you check why the lint python pipeline is failing?

**Comment by ming-tsai** [comment]
Hi @cclauss,
Does this necessary?

**Review by ming-tsai — APPROVED** [review]

**Comment by ming-tsai** [comment]
There is a conflict

**Review by sridhar-5 — APPROVED** [review]
LGTM! Can be merged if there is no conflict.

**Pull request merged**
