### PR TITLE
chore(Go): maximum subarray sum

### PR DESCRIPTION
**Pull request by himsngh**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

Added a new folder for arrays in golang.
In that arrays added a new problem to find the  maximum subarray sum  (using kadane's algorithm).

**Other information:**

### CODE REVIEW

**Comment by atin** [comment]
Hey, can you remove the .idea files?

**Review by atin — CHANGES_REQUESTED** [review]
Can you remove the .idea files? They are not necessary for the repo.

**Comment by himsngh** [comment]
> Can you remove the .idea files? They are not necessary for the repo. Also sorry for the late review I had a few exams :)

Hey, I have done that.

**Comment by atin** [comment]
@ming-tsai can you run the workflows?

**Comment by ming-tsai** [comment]
Hi @himsngh,
Please fix the ReviewDog error [messages](https://github.com/MakeContributions/DSA/actions/runs/808767629)

**Comment by himsngh** [comment]
> Hi @himsngh,
> Please fix the ReviewDog error [messages](https://github.com/MakeContributions/DSA/actions/runs/808767629)

Okay done

**Review by ming-tsai — APPROVED** [review]

**Pull request merged**
