### PR TITLE
chore(CPlusPlus): array removing duplicates in place

### PR DESCRIPTION
**Pull request by ShambhaviSharma0110**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

Removing array duplicates without using any extra space in C++
https://leetcode.com/problems/remove-duplicates-from-sorted-array/

**Other information:**

### CODE REVIEW

**Review by Arsenic-ATG — CHANGES_REQUESTED** [review]
Sorry but only complete programs ( along with some simple tests ) are accepted here. 

leetcode solutions as is are not considered as complete programs and thus doesn't qualify.

you might wanna read our [contribution guidelines](https://github.com/MakeContributions/DSA#contribution-guidelines) for more info.

**Comment by ming-tsai** [comment]
Hi @ShambhaviSharma0110,
Any update?

**Comment by ming-tsai** [comment]
You have to push on the `main` of your repo

**Comment by ShambhaviSharma0110** [comment]
> You have to push on the `main` of your repo

Hey! I did that...

**Comment by ming-tsai** [comment]
> > You have to push on the `main` of your repo
> 
> Hey! I did that...
> 

Does it throws a erro? Which is the erro?

**Comment by ming-tsai** [comment]
Hi @ShambhaviSharma0110,
It has not been updated before June 1, it will be closed

**Comment by Arsenic-ATG** [comment]
## 🚧 Closing this issue due to long inactivity. 

is someone want to work on this then feel free to either open a new issue or PR regarding the same.

**Pull request closed without merging**
