### PR TITLE
chore(CPlusPlus): add quick-select

### PR DESCRIPTION
**Pull request by IAmTamal**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

I have added a new algorithm popularly known as the "quick-select" or Partition algorithm.

**Other information:**

### CODE REVIEW

**Review by IAmTamal — COMMENTED** [review]
changed some names like "n" to "size" and so on..

**Review by aayushjain7 — CHANGES_REQUESTED** [review]
Great job with the algorithm. Also, add the algorithm to its corresponding readme.MD file.

**Comment by IAmTamal** [comment]
> Great job with the algorithm. Also, add the algorithm to its corresponding readme.MD file.

Sure, sir.

**Review by aayushjain7 — APPROVED** [review]
Great work 💯

**Pull request merged**
