### PR TITLE
Add jump search py

### PR DESCRIPTION
**Pull request by anupam-b**

### CODE REVIEW

**Comment by ming-tsai** [comment]
Hi @Arsenic-ATG or @akrish4,
Could you help me to check this?

**Review by Arsenic-ATG — APPROVED** [review]

**Review by Arsenic-ATG — APPROVED** [review]
functionally works
It would be better if you would have created a check too see if the input array is already sorted or not ( maybe a separate function for the same and not affect the core functionality of the `jump_search()` function ) because now it gives wrong output instead of an error messages that unsorted array was provided at first place

but as far as algorithm is concerned then it is correctly implemented and is working for all of the used cases that I have tested upon.

**Comment by anupam-b** [comment]
Thank you for the feedback.
I will add a function that checks for sorted list.

**Review by Arsenic-ATG — APPROVED** [review]

**Comment by ming-tsai** [comment]
Hi @anupam-b,
Nice work 🎉, and welcome to our team.

> you could see the invitation on this [page](https://github.com/MakeContributions)

**Pull request merged**
