### PR TITLE
chore(Java): add square root using binary search

### PR DESCRIPTION
**Pull request by mohitchakraverty**
**PR Checklist:**
- [x] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [x] My addition is on refer on the language README.md file
- [x] My addition does not have a spelling problem
- [x] My submission has a proper and user-friendly description of the algorithm
- [x] My submission has the time complexity of the algorithm
- [x] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**
I have added a Java program to find square root of a number using Binary Search i.e decrease and conquer approach

**Other information:**

### CODE REVIEW

**Comment by mohitchakraverty** [comment]
@ming-tsai  Waiting for approval :)

**Comment by mohitchakraverty** [comment]
@aayushjain7 Waiting for your approval

**Comment by ming-tsai** [comment]
> @aayushjain7 Waiting for your approval

I guess he is busy, I will be checking this pull request in this weekend.

**Review by ming-tsai — CHANGES_REQUESTED** [review]
Hi @mohitchakraverty,
Nice works, but please fix the spelling error.
```md
./algorithms/Java/Maths/square-root.java:42: upto ==> up to
```

**Comment by mohitchakraverty** [comment]
@ming-tsai Done!

**Review by ming-tsai — APPROVED** [review]

**Pull request merged**
