### PR TITLE
enh(Python): nth_fibonacci_number

### PR DESCRIPTION
**Pull request by bishtanuj**
**PR Checklist:**
- [x] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [x] My addition is on refer on the language README.md file
- [x] My addition does not have a spelling problem
- [x] My submission has a proper and user-friendly description of the algorithm
- [x] My submission has the time complexity of the algorithm
- [x] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

### CODE REVIEW

**Review by PSCoder10462 — COMMENTED** [review]
Hey @bishtanuj !
This code is just plain recursion and will work in exponential time complexity.
A code using dynamic programming(memoization) already exists that is far better and shall work in O(n) time and O(n) space.
However, there exists and algorithm to improve space complexity of the code, where you will need O(1) auxiliary space by just maintaining three variables (you can research rest). 
But unfortunately it doesn't fall under the category "RECURSION"!
Hence, no point in this PR i suppose.

**Comment by bishtanuj** [comment]
> Hey @bishtanuj ! This code is just plain recursion and will work in exponential time complexity. A code using dynamic programming(memoization) already exists that is far better and shall work in O(n) time and O(n) space. However, there exists and algorithm to improve space complexity of the code, where you will need O(1) auxiliary space by just maintaining three variables (you can research rest). But unfortunately it doesn't fall under the category "RECURSION"! Hence, no point in this PR i suppose.

The existing code is for the nth Fibonacci number but this program is for Fibonacci series

**Comment by bishtanuj** [comment]
This PR is about Fibonacci Series, kindly do not confuse it with nth_fibonacci_number, as it is different from it

**Comment by bishtanuj** [comment]
> This PR is about Fibonacci Series, kindly do not confuse it with nth_fibonacci_number, as it is different from it

@ming-tsai sir has changed the name of the PR, but the PR is about Fibonacci Series not nth number

**Comment by PSCoder10462** [comment]
> This PR is about Fibonacci Series, kindly do not confuse it with nth_fibonacci_number, as it is different from it

I know full well what your code is meant to do. However, that isn't quite the issue here.
Your current code won't even generate the series of 100 numbers. Just try running it.
You need to optimize your code using dp if at all you want to put it under the category of recursion!

**Review by Arsenic-ATG — CHANGES_REQUESTED** [review]
A program implementing fibonacci series also exists in the repository (  [algorithm/dynamic programming/fibonacci_series.py](https://github.com/MakeContributions/DSA/blob/main/algorithms/Python/dynamic_programming/fibonacci_series.py) )

the pre-existing implementation is far more optimised than plain old recursion implemented by this PR.

**Pull request closed without merging**
