### PR TITLE
chore(CPlusPlus): add sum of right leaves in binary tree

### PR DESCRIPTION
**Pull request by ryanoliverdev**
**PR Checklist:**
- [x] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [x] My addition is on refer on the language README.md file
- [x] My addition does not have a spelling problem
- [x] My submission has a proper and user-friendly description of the algorithm
- [x] My submission has the time complexity of the algorithm
- [x] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**
Added algorithm to recursively traverse through a binary tree to get the sum of all right leaves

**Other information:**

### CODE REVIEW

**Comment by ryanoliverdev** [comment]
I have to update the comments in my code, it uses a queue not recursion.

**Comment by Ashborn-SM** [comment]
@ryanoliverdev update the readme as well

**Comment by ming-tsai** [comment]
Hi @ryanoliverdev,
Any update?

**Comment by ryanoliverdev** [comment]
@ming-tsai @Ashborn-SM Hi, sorry I just saw your message. I've updated both the readme and updated the comments on my code. Thank you

**Review by Ashborn-SM — APPROVED** [review]

**Pull request merged**
