### PR TITLE
chore(CPlusPlus): add index of smallest element in array

### PR DESCRIPTION
**Pull request by shefali12-ab**
**PR Checklist:**
- [X] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [X] My addition is on refer on the language README.md file
- [X] My addition does not have a spelling problem
- [X] My submission has a proper and user-friendly description of the algorithm
- [X] My submission has the time complexity of the algorithm
- [X] My submission has sample input-output of the program (NOT FOR PYTHON)
- [X] The description does not end with punctuation

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [X] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

I have added a source code to a problem that is to find smallest index of element of array in C++.

**Other information:**

#583

### CODE REVIEW

**Comment by UG-SEP** [comment]
> > Please wait for few hours I will review it soon
> 
> Sure sir

Please don't me sir @shefali12-ab 
I do not deserve it right now
You can call me UG❤

**Comment by UG-SEP** [comment]
Please add your program name and link in the c++ [readme](https://github.com/MakeContributions/DSA/blob/main/algorithms/CPlusPlus/README.md) file

So then I can review it further😊

**Comment by shefali12-ab** [comment]
> Please add your program name and link in the c++ [readme](https://github.com/MakeContributions/DSA/blob/main/algorithms/CPlusPlus/README.md) file
> 
> So then I can review it further😊
> 
> PS: Sorry for the late review

No problem, I have made changes.

**Comment by shefali12-ab** [comment]
It is having Resolve Conflict please look into it once.

**Pull request merged**
