### PR TITLE
chore(Python): add Fibonacci

### PR DESCRIPTION
**Pull request by Mo-Shakib**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

### CODE REVIEW

**Comment by Mo-Shakib** [comment]
I didn't understand what to to! Can you please explain?

**Comment by sridhar-5** [comment]
Hello, Sorry wasn't active from a few days. checking this now.

**Review by sridhar-5 — CHANGES_REQUESTED** [review]
Please update the readme file with the added algorithms name following the file naming guidelines.

**Comment by sridhar-5** [comment]
Please read the organisations contribution guidelines here. [https://github.com/MakeContributions/DSA](url)

**Comment by ming-tsai** [comment]
Hi @Mo-Shakib,
Any updated?

**Comment by Mo-Shakib** [comment]
@sridhar-5  I just update the readme.md file, please check now.

**Comment by sridhar-5** [comment]
> @sridhar-5 I just update the readme.md file, please check now.

I cannot see any updates done to the readme.

**Comment by ming-tsai** [comment]
Hi @Mo-Shakib,
Need help?

**Comment by Mo-Shakib** [comment]
I'm making a new pull request. Actually it's very first time that I'm using github pull requests. :)

**Comment by ming-tsai** [comment]
Ok, if you need help you could chat on this [discussion](https://github.com/MakeContributions/DSA/discussions/383)

**Pull request closed without merging**
