### PR TITLE
enh(Java): add comments for binary search

### PR DESCRIPTION
**Pull request by rakshitgondwal**
Improved the code by adding the explanation of using  (l + (r - l)) rather than using (l - r) while searching for the mid element.

**PR Checklist:**
- [ ] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [ ] My addition is on refer on the language README.md file
- [ ] My addition does not have a spelling problem
- [ ] My submission has a proper and user-friendly description of the algorithm
- [ ] My submission has the time complexity of the algorithm
- [ ] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

### CODE REVIEW

**Review by TawfikYasser — APPROVED** [review]
Thanks, @rakshitgondwal for the enhancement. 👍🏻
You may also add an example to support your comment.

> Tawfik Y.

**Comment by rakshitgondwal** [comment]
Thanks, @TawfikYasser for reviewing my PR.

I guess by providing the proper logic behind the code would really help others to build the proper intuition related to that topic.

In my PR , I've added the explanation to why we use ( l + (r - l) / 2 ) while searching for the mid in binary search, which I read about on various other websites such as-

https://ai.googleblog.com/2006/06/extra-extra-read-all-about-it-nearly.html
https://stackoverflow.com/questions/6735259/calculating-mid-in-binary-search
https://discuss.codechef.com/t/why-we-use-mid-low-high-low-2-in-binary-search-algorithms/88933

**Comment by ming-tsai** [comment]
Hi @rakshitgondwal,
Please add this file on the `readme.md` of Java.

**Comment by ming-tsai** [comment]
> Hey @ming-tsai 
> Can you please guide me how should I do that?
> Actually I am new to open source and this was my first contribution.
> I would be very grateful if you could help me out.

Hi @rakshitgondwal,
Please add the index to this file https://github.com/rakshitgondwal/DSA/blob/patch-1/algorithms/Java/README.md

**Pull request merged**
