### PR TITLE
chore(Go): Add reverse array

### PR DESCRIPTION
**Pull request by leonardogonfiantini**
**PR Checklist:**
- [x] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [x] My addition is on refer on the language README.md file
- [x] My addition does not have a spelling problem
- [x] My submission has a proper and user-friendly description of the algorithm
- [x] My submission has the time complexity of the algorithm
- [x] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

Added reverse-array for go language

**Other information:**

If i have made some mistakes, please let me know i happy to fix it

### CODE REVIEW

**Comment by leonardogonfiantini** [comment]
I have made mistakes?

**Comment by ayo-ajayi** [comment]
is this a test function or a function for reversing an array?

use a *_test.go filename for testing using the "testing" package

if it's not a test file, pass the array as an argument of the function and make sure the name of the function does not start with "Test".

Cheers.

**Comment by leonardogonfiantini** [comment]
I have changed the function, yes is not a test function but a function for reverse an array, i have removed the test in the function name and pass an array as an argument of the function.
Thank you for your review!

**Review by ayo-ajayi — APPROVED** [review]

**Comment by leonardogonfiantini** [comment]
Why the code spell failed?

**Pull request merged**
