### PR TITLE
chore(CPlusPlus): add cycle in graph

### PR DESCRIPTION
**Pull request by kartikeya100**
**What kind of change does this PR introduce?** (check at least one)

- [X] New algorithm
- [ ] Bugfix
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**
Added C++ Algorithm to check if Directed graph contains a cycle.

**Other information:**
fix: #377

### CODE REVIEW

**Comment by UG-SEP** [comment]
@kartikeya100 Thanks for opening PR
but please first attach the issue you are working 
by writing fix: #isssue_number in Other information

**Comment by kartikeya100** [comment]
Should be fixed now.

**Review by aayushjain7 — COMMENTED** [review]
make changes in the readme.MD file

**Comment by ming-tsai** [comment]
@kartikeya100 what happened?

**Pull request closed without merging**
