### PR TITLE
Added bubble sort algorithm in C++

### PR DESCRIPTION
**Pull request by Roshaen**

### CODE REVIEW

**Comment by ming-tsai** [comment]
@akrish4 could you help me to check this?

**Comment by akrish4** [comment]
> @akrish4 could you help me to check this?

yes sure @ming-tsai  , actually i was quite busy so I couldn't see into it before

**Review by akrish4 — APPROVED** [review]

**Comment by ming-tsai** [comment]
> > @akrish4 could you help me to check this?
> 
> yes sure @ming-tsai  , actually i was quite busy before 

Ok, sorry

**Comment by ming-tsai** [comment]
Hi @Roshaen,
Thanks for your contributions and welcome to our team

**Pull request merged**
