### PR TITLE
chore(CPlusPlus): add odd even

### PR DESCRIPTION
**Pull request by kumarsyadav2**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [x] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**
A program that used to find whether the number is even or odd.

### CODE REVIEW

**Comment by kumarsyadav2** [comment]
> The PR is full of redundant commits which needs to be cleaned before merging.
> 
> Here's a possible way to fix this :
> 
> 1. Create a new branch
> 2. Reset that branch to the point that it becomes even with `MakeContributions/DSA:main`
> 3. Cherry pick the commits that you want in the new branch branch
> 4. Create a PR from that new branch

Does it mean that i have to create everytime a new branch for making pull request.

**Comment by kumarsyadav2** [comment]
hey @Arsenic-ATG i don't know how to fix this! Do i need to close this and make a new pull request from new branch?
or it can be fixed without closing this PR? i don't know much about this, can you please suggest me any blog or video regarding this.

**Comment by Arsenic-ATG** [comment]
> > The PR is full of redundant commits which needs to be cleaned before merging.
> > Here's a possible way to fix this :
> > 
> > 1. Create a new branch
> > 2. Reset that branch to the point that it becomes even with `MakeContributions/DSA:main`
> > 3. Cherry pick the commits that you want in the new branch branch
> > 4. Create a PR from that new branch
> 
> Does it mean that i have to create everytime a new branch for making pull request.

Yes, create a new branch with changes in it and then simply dispose it as soon as it gets merged in the main ( This is actually way easier than it sounds and saves a ton of time )

---

> hey @Arsenic-ATG i don't know how to fix this! Do i need to close this and make a new pull request from new branch?
> or it can be fixed without closing this PR? i don't know much about this, can you please suggest me any blog or video regarding this.

No need to close the PR, If you want, I can also force overwrite your fork to keep it in sync with `DSA:main` repo but it will make you loose your new changes ( even-odd programs ) you wrote at the end so it's recommended to create a backup of those 2 commits or rewrite those changes once the reset takes place.

Once your fork's main is fixed, it would be just a matter of creating a new branch from that fork and apply changes to it, we can then change the source of this PR to point to your new branch instead of master. 

Just tell me when you are ready and we should be good to go.

**Comment by ming-tsai** [comment]
Hi @kumarsyadav2,
Please solve the conflict problem.

**Comment by Arsenic-ATG** [comment]
@kumarsyadav2 your main branch is now in sync with remote 

The PR is closed as now there are no changes in the fork.

You should now to be good to go and update a new branch with your changes in it. 
Either open a new PR with those changes or tell me here when the changes are ready and we shall re-route this PR to be based out of that new branch.

**Comment by Jaraxxxx** [comment]
@ming-tsai  I am willing to contribute to this issue can you assign me this issue

**Pull request closed without merging**
