### PR TITLE
enh(CPlusPlus): balanced-parenthesis

### PR DESCRIPTION
**Pull request by UG-SEP**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] New algorithm
- [x] Optimization in previous algorithms
- [x] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**
add a proper comment in the program and replace the switch statement with the if statement as switch cases do the same work that only one if condition does as well as make the program much more user friendly by providing a better UI than before

**Other information:**

closes: #375

### CODE REVIEW

**Review by aayushjain7 — CHANGES_REQUESTED** [review]
> Great! but also make changes in the readme file

may I know that what types of changes because the name and the link of the program pre-exist there

**Comment by aayushjain7** [comment]
> > Great! but also make changes in the readme file
> 
> may I know that what type of changes because the name and the link of the program pre-exist there

my bad

**Review by aayushjain7 — APPROVED** [review]
great work!!

**Comment by UG-SEP** [comment]
> > > Great! but also make changes in the readme file
> > 
> > 
> > may I know that what type of changes because the name and the link of the program pre-exist there
> 
> my bad

It happens sometimes 😅

**Pull request merged**
