### PR TITLE
enh(CPlusPlus): add binary search

### PR DESCRIPTION
**Pull request by rakshitgondwal**
Improved the code by adding the explanation of using  (l + (r - l)) rather than using (l - r) while searching for the mid element.

**PR Checklist:**
- [ ] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [ ] My addition is on refer on the language README.md file
- [ ] My addition does not have a spelling problem
- [ ] My submission has a proper and user-friendly description of the algorithm
- [ ] My submission has the time complexity of the algorithm
- [ ] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [x] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

### CODE REVIEW

**Comment by Arsenic-ATG** [comment]
> Please add the index to this file https://github.com/rakshitgondwal/DSA/blob/patch-3/algorithms/CPlusPlus/README.md

It's just an addition of comment in an already existing program and not addition of a new program.

**Comment by rakshitgondwal** [comment]
How should I proceed with this then? @Arsenic-ATG

**Comment by Arsenic-ATG** [comment]
> How should I proceed with this then? @Arsenic-ATG

the changes look fine to me, looks like there is some misunderstanding here.

just make sure you fill the PR checklist properly in any future contribution, it reduces the chances of happening something like this later down the line.

**Comment by rakshitgondwal** [comment]
Oh, I'm sorry for the mistake! @Arsenic-ATG 
I'll keep this in my mind in future for sure.
Thanks for helping out.

**Comment by ming-tsai** [comment]
> > Please add the index to this file https://github.com/rakshitgondwal/DSA/blob/patch-3/algorithms/CPlusPlus/README.md
> 
> It's just an addition of comment in an already existing program and not addition of a new program.
> 
> More appropriately it comes under **refactor** section of PR checklist.

Ok, sorry I thought it was a new change

**Pull request merged**
