### PR TITLE
chore(Python): add diameter of binary tree

### PR DESCRIPTION
**Pull request by geekboi777**
**PR Checklist:**
- [ ] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [ ] My addition is on refer on the language README.md file
- [ ] My addition does not have a spelling problem
- [ ] My submission has a proper and user-friendly description of the algorithm
- [ ] My submission has the time complexity of the algorithm
- [ ] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

### CODE REVIEW

**Comment by ming-tsai** [comment]
Hi @geekboi777,
Please complete the pull request checklist

**Review by sridhar-5 — CHANGES_REQUESTED** [review]
The GIven algorithm returns '4' but the result that is actually expected is '3'.  Length of the diameter of binary tree is the longest distance between any two nodes in a binary tree. i was wondering on how the distance is 4. clearly the longest path is 4 -> 2 -> 1 - > 3. so the length is 3. can you please recheck the code.

**Comment by ming-tsai** [comment]
> **PR Checklist:**
> 
> * [ ]  My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
> * [ ]  My addition is on refer on the language README.md file
> * [ ]  My addition does not have a spelling problem
> * [ ]  My submission has a proper and user-friendly description of the algorithm
> * [ ]  My submission has the time complexity of the algorithm
> * [ ]  My submission has sample input-output of the program (NOT FOR PYTHON)
> 
> **What kind of change does this PR introduce?** (check at least one)
> 
> * [ ]  Bugfix
> * [ ]  New algorithm
> * [ ]  Optimization in previous algorithms
> * [ ]  Code style update
> * [ ]  Refactor
> * [ ]  Documentation
> * [ ]  Other, please describe:
> 
> **Briefly describe the changes in this PR**
> 
> **Other information:**

Hi @geekboi777,
Please completed the pull request checklist, and this will be a valid pull request

**Comment by ming-tsai** [comment]
Hi @geekboi777,
Any updates?

**Comment by ming-tsai** [comment]
Hi @geekboi777,
This pull request will be closed when making a change please re-open this pull request.

**Pull request closed without merging**
