### PR TITLE
Kadane's Algorithm

### PR DESCRIPTION
**Pull request by aayushjain7**

### CODE REVIEW

**Review by TawfikYasser — APPROVED** [review]
LGTM ✨

**Comment by aayushjain7** [comment]
Thanks.

**Comment by ming-tsai** [comment]
Hi @aayushjain7,
Nice work, thanks for your contributions, and welcome to our team
> The invitation [link](https://github.com/MakeContributions)
> If you are interested in the contribution our new project here is the [link](https://github.com/MakeContributions/ideahub)

**Comment by aayushjain7** [comment]
Thank you! @ming-tsai

**Pull request merged**
