### PR TITLE
chore(CPlusPlus): add kadanes

### PR DESCRIPTION
**Pull request by Hemangpandey**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

### CODE REVIEW

**Comment by ming-tsai** [comment]
Hi @Hemangpandey,
Which is your change?

**Comment by Hemangpandey** [comment]
Yes I have Added A code for Kadane's Algorithm in cpp

**Review by Arsenic-ATG — CHANGES_REQUESTED** [review]
An implementation of Kadane's Algorithm already exists in the repository [here](https://github.com/MakeContributions/DSA/blob/main/algorithms/CPlusPlus/Arrays/max-subarray-sum.cpp)

If you want to improve it in some ways, then it is recommended to update that particular file in order to qualify.

**Comment by Hemangpandey** [comment]
I'll be back later

**Pull request closed without merging**
