### PR TITLE
add merge-sort

### PR DESCRIPTION
**Pull request by divesharora**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**
Added merge sort implementation in JavaScript.

**Other information:**

### CODE REVIEW

**Review by ming-tsai — CHANGES_REQUESTED** [review]
Hi @divesharora,
Please add the algorithm to readme on sorting folder

**Review by ming-tsai — APPROVED** [review]
Hi @divesharora,
Nice work, and welcome to our team
> The invitation [link](https://github.com/MakeContributions)

**Comment by ming-tsai** [comment]
Sorry about this, fix the linter problem then open a new pull request for Merge Sort?

**Comment by divesharora** [comment]
> Sorry about this, fix the linter problem then open a new pull request for Merge Sort?

sure will do this

**Pull request merged**
