### PR TITLE
chore(C): added a linkedlist

### PR DESCRIPTION
**Pull request by anandhu720**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [X] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

I added a code in C language of linked list,which condains most of the operations done in a singly linked list in single file.It will be helpful for beginners to study linked list.

**Other information:**

### CODE REVIEW

**Comment by anandhu720** [comment]
@ming-tsai i changed tht spelling mistakes sir

**Comment by anandhu720** [comment]
@ming-tsai I changed that spelling mistakes sir

**Comment by ming-tsai** [comment]
> @ming-tsai I changed that spelling mistakes sir
> 

Nice work

**Comment by anandhu720** [comment]
What i need to do next

**Review by Arsenic-ATG — CHANGES_REQUESTED** [review]
I appreciate your handwork that you have put in these algorithms. 

But these are a lot of algorithms for one file, it is recommended to implement one algorithm ( or at most one class of algorithms like searching, sorting etc ) in one file. 
having tons of algorithm in one file not only makes it difficult to test and review the program, but also makes it hard for future contributors to find a topic to contribute.

it is recommended to split this file in multiple files each targeted to solve a particular problem. ( like one targeted to reverse a linked list in different manners, one targeted to perform search in linked list etc. )

Also don't forget to update the [index readme](https://github.com/MakeContributions/DSA/blob/main/algorithms/C/README.md) of `Algorithm/C` with your creations/s in the list.

**Comment by anandhu720** [comment]
ok

**Pull request closed without merging**
