### PR TITLE
chore(CPlusPlus): add Huffman algorithms

### PR DESCRIPTION
**Pull request by adeity21**
**PR Checklist:**
- [x] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [x] My addition is on refer on the language README.md file
- [x] My addition does not have a spelling problem
- [x] My submission has a proper and user-friendly description of the algorithm
- [x] My submission has the time complexity of the algorithm
- [x] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [x] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

### CODE REVIEW

**Review by Ashborn-SM — APPROVED** [review]
Good work

**Comment by ming-tsai** [comment]
Hi @adeity21,
Please add this file reference to this [file](https://github.com/adeity21/DSA/blob/main/algorithms/CPlusPlus/README.md)

**Review by ming-tsai — CHANGES_REQUESTED** [review]
Hi @adeity21,
Please add this file reference to this [file](https://github.com/adeity21/DSA/blob/main/algorithms/CPlusPlus/README.md)

**Comment by ming-tsai** [comment]
Hi @adeity21,
This pull request will be closed, any updates please reopen this pull request.

**Pull request closed without merging**
