### PR TITLE
Added Insertion and Selection sort to the python folders.

### PR DESCRIPTION
**Pull request by acdlee**
Added Insertion and Selection sort for Python. 
I'd be interested in contributing graph search algorithms and possibly other algorithms; I just need to know if you have a desired graph representation or if I can take creative control on the implementation. Thanks.

### CODE REVIEW

**Review by Arsenic-ATG — CHANGES_REQUESTED** [review]
**Selection sort** fails on input like

```python
A = [5, 4, 3, 2, 1]
```
for above used case, your program yields the following output
```
Sorted array: 
	1
	3
	2
	4
	5
```
The fix is quite simple and I leave it on you to figure out on your own, if you fail to figure it out then do let me know, I will help you with the same 🙂.

----

As for **insertion sort** code, it is working perfectly fine ✅

**Comment by acdlee** [comment]
> **Selection sort** fails on input like
> 
> ```python
> A = [5, 4, 3, 2, 1]
> ```
> 
> for above used case, your program yields the following output
> 
> ```
> Sorted array: 
> 	1
> 	3
> 	2
> 	4
> 	5
> ```
> 
> The fix is quite simple and I leave it on you to figure out on your own, if you fail to figure it out then do let me know, I will help you with the same 🙂.
> 
> As for **insertion sort** code, it is working perfectly fine ✅

**Comment by acdlee** [comment]
> **Selection sort** fails on input like
> 
> ```python
> A = [5, 4, 3, 2, 1]
> ```
> 
> for above used case, your program yields the following output
> 
> ```
> Sorted array: 
> 	1
> 	3
> 	2
> 	4
> 	5
> ```
> 
> The fix is quite simple and I leave it on you to figure out on your own, if you fail to figure it out then do let me know, I will help you with the same 🙂.
> 
> As for **insertion sort** code, it is working perfectly fine ✅

Resolved issues with the bounds; I took for granted the conversion from pseudocode to the range function. Thanks for finding this!

**Review by Arsenic-ATG — APPROVED** [review]

**Comment by paulsonjpaul** [comment]
> I'd be interested in contributing graph search algorithms and possibly other algorithms; I just need to know if you have a desired graph representation or if I can take creative control on the implementation. Thanks.

@ming-tsai, can you please answer his question?

**Comment by ming-tsai** [comment]
Yes, you can do it @acdlee

**Pull request merged**
