### PR TITLE
chore(Java): add cyclically rotate on arrays

### PR DESCRIPTION
**Pull request by pratik-a**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

### CODE REVIEW

**Review by TawfikYasser — CHANGES_REQUESTED** [review]
Hello @pratik-a 
Thanks for your awesome work,

We need to fix some issues first:

1. The output for the algorithm is: 👇
Given Array is
1 2 3 4 5 6 7 
Rotated Array is
7 1 2 3 4 5 6 

I think the output is not the required!

2. Please add the algorithm to the docs.

**Comment by ming-tsai** [comment]
Hi @pratik-a,
Any update?

**Comment by pratik-a** [comment]
> Hi @pratik-a,
> Any update?

will update in docs

**Comment by ming-tsai** [comment]
> > Hi @pratik-a,
> > Any update?
> 
> will update in docs

Ok, waiting for your update

**Comment by ming-tsai** [comment]
Hi @pratik-a,
This pull request will be closed, any updates please re-open this pull request.

**Pull request closed without merging**
