### PR TITLE
chore(CPlusPlus): add elements appear thrice

### PR DESCRIPTION
**Pull request by raunak321321**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

### CODE REVIEW

**Review by aayushjain7 — CHANGES_REQUESTED** [review]
Also, update the readme.MD file for this program

**Comment by raunak321321** [comment]
ok @aayushjain7 i will update readme

**Comment by raunak321321** [comment]
@aayushjain7 i update readme u can check

**Review by aayushjain7 — APPROVED** [review]
nice work

**Pull request merged**
