### PR TITLE
chore(CPlusPlus): add binary power

### PR DESCRIPTION
**Pull request by angshudas**
**PR Checklist:**
- [x] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [x] My addition is on refer on the language README.md file
- [x] My addition does not have a spelling problem
- [x] My submission has a proper and user-friendly description of the algorithm
- [x] My submission has the time complexity of the algorithm
- [x] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

### CODE REVIEW

**Comment by angshudas** [comment]
Hey, I am new to github. Please let me know if there are some changes to be made in this PR.

**Review by Ashad001 — CHANGES_REQUESTED** [review]
Correct the description on line 6 
```diff
+ return 1 
```
and can you add space and time complexity of your algorithm in description?

**Review by Arsenic-ATG — CHANGES_REQUESTED** [review]
The PR also need to update the proper README.md with the entry of the program in it.

For your particular program it would be [algorithms/CPlusPlus/README.md](https://github.com/angshudas/DSA/blob/binary-power/algorithms/CPlusPlus/README.md) under the Maths section

**Comment by ming-tsai** [comment]
Hi @angshudas,
This is duplicated pull request #810

**Pull request closed without merging**
