### PR TITLE
Add Python doctests to binary search

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Review by aayushjain7 — APPROVED** [review]

**Comment by ming-tsai** [comment]
Hi @cclauss,
Does this necessary?

**Comment by cclauss** [comment]
Yes.  This is a sub task of #169

**Review by cyberwizard1001 — APPROVED** [review]
Was about to mention the missing mid variable but found it. Doctests work, code seems good to go, @ming-tsai and @cclauss.

**Comment by ming-tsai** [comment]
> Was about to mention the missing mid variable but found it. Doctests work, code seems good to go, @ming-tsai and @cclauss. 

I mean you have had move all python file to its folder, so I thought you should make change on that folder, no on this one.

**Comment by ming-tsai** [comment]
> Yes.  This is a subtask of #169

I mean you have had move all python file to its folder, so I thought you should make change on that folder, no on this one.

**Comment by cclauss** [comment]
Yes.  That I why made the request in the commit message of #207 that was ignored.

**Review by aayushjain7 — APPROVED** [review]
Lgtm!!

**Comment by cyberwizard1001** [comment]
Close the PR?

**Comment by aayushjain7** [comment]
Can we merge? Or should wait?

**Comment by cclauss** [comment]
Wait for what?

**Pull request merged**
