### PR TITLE
Multiplication Algorithms - Karatsuba Multiplication Added in Python and CPP

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ming-tsai** [comment]
Hi @Arsenic-ATG and @akrish4,
One of you could help me to check this PR?

**Comment by Arsenic-ATG** [comment]
> Hi @Arsenic-ATG and @akrish4,
> One of you could help me to check this PR?

@ming-tsai , I will review it by tomorrow.

**Comment by atin** [comment]
I've some a big testcase (multiplication of two ~5000 digit long numbers). You can find them [here](https://github.com/atin/Algorithms/tree/main/Karatsuba%20Multiplication).

**Review by Arsenic-ATG — APPROVED** [review]
Functionally working and correctly implemented ✅

The same minor documentation problem as already discusses in your [previous PR](https://github.com/MakeContributions/DSA/pull/35)

**Pull request merged**
