### PR TITLE
chore(Java): add breadth-first search

### PR DESCRIPTION
**Pull request by thuongtruong1009**
add BFS searching

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

### CODE REVIEW

**Comment by thuongtruong1009** [comment]
thanks you!

**Review by TawfikYasser — CHANGES_REQUESTED** [review]
Hi @thuongtruong1009 
_**Thanks for your effort**_

Please fix the following:
* Spaces/Indentation in the code.
* File path (\Code\Java\BFS.txt) make it generic.
* Add the algorithm to the README.md file [here](https://github.com/MakeContributions/DSA/tree/main/algorithms/Java#searching).

**Comment by ming-tsai** [comment]
Hi @thuongtruong1009,
Any updated?

**Comment by ming-tsai** [comment]
Hi @thuongtruong1009,
This pull request will be closed, any updates please re-open this pull request.

**Pull request closed without merging**
