### PR TITLE
chore(Python): shell sort algorithm

### PR DESCRIPTION
**Pull request by Ayushparikh-code**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

 added shell sort in sorting category of python 
**Other information:**
 updated readme too

### CODE REVIEW

**Review by Ayushparikh-code — COMMENTED** [review]
👍

**Review by sridhar-5 — CHANGES_REQUESTED** [review]
Nice Work @Ayushparikh-code. It would be Nice if you add the time complexity.

**Review by Ayushparikh-code — COMMENTED** [review]
Ok

**Comment by Ayushparikh-code** [comment]
> Nice Work @Ayushparikh-code. It would be Nice if you add the time complexity.

Added time complexity inside file in the form of comment's 👍 now approve and merge it

**Review by sridhar-5 — APPROVED** [review]
Nice Work @Ayushparikh-code.

**Comment by ming-tsai** [comment]
> **What kind of change does this PR introduce?** (check at least one)
> 
> * [ ]  Bugfix
> * [ ✔] New algorithm
> * [ ]  Optimization in previous algorithms
> * [ ]  Code style update
> * [ ]  Refactor
> * [ ]  Documentation
> * [ ]  Other, please describe:
> 
> **Briefly describe the changes in this PR**
> 
> added shell sort in sorting category of python
> **Other information:**
> updated readme too

Hi @Ayushparikh-code,
Everything is ok, but please fix this checklist, here is the documentation of markdown [tasklist](https://www.markdownguide.org/extended-syntax/#task-lists)

**Comment by Ayushparikh-code** [comment]
> > **What kind of change does this PR introduce?** (check at least one)
> > 
> > * [ ]   Bugfix
> > * [ ✔] New algorithm
> > * [ ]   Optimization in previous algorithms
> > * [ ]   Code style update
> > * [ ]   Refactor
> > * [ ]   Documentation
> > * [ ]   Other, please describe:
> > 
> > **Briefly describe the changes in this PR**
> > added shell sort in sorting category of python
> > **Other information:**
> > updated readme too
> 
> Hi @Ayushparikh-code,
> Everything is ok, but please fix this checklist, here is the documentation of markdown [tasklist](https://www.markdownguide.org/extended-syntax/#task-lists)

Done ✅

**Pull request merged**
