### PR TITLE
[Docs] Add how to make your First Contributions

### PR DESCRIPTION
**Pull request by Amisha-Mohapatra**
@ming-tsai kindly checkout this

### CODE REVIEW

**Comment by paulsonjpaul** [comment]
The documentation has many similarities with firstcontributions. Please edit it so it looks original 😉

**Review by ming-tsai — APPROVED** [review]

**Review by ming-tsai — CHANGES_REQUESTED** [review]
Hi @Amisha-Mohapatra,
Could you make changes to the below checklist?

- [x] Rename the file to `CONTRIBUTING.md`
- [ ] Change the title `First Contribution` to `How to make your first contributions?`
- [ ] Linked it on the section of contribution guidelines with the title `How to make your first contributions?`

**Comment by Amisha-Mohapatra** [comment]
@ming-tsai can you brief about the last change? I am a bit confused how to achieve.. @paulsonjpaul kindly help

**Review by ming-tsai — APPROVED** [review]
Good Job @Amisha-Mohapatra

**Pull request merged**
