### PR TITLE
chore(Python): added 0/1 knapsack problem

### PR DESCRIPTION
**Pull request by canhuynh1998**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**
0/1 Knapsack Problem using Dynamic Programming and implemented using Python

### CODE REVIEW

**Comment by canhuynh1998** [comment]
Can someone let me know what test did I fail? I am not really sure.

**Comment by ming-tsai** [comment]
> Can someone let me know what test did I fail? I am not really sure.

Don't worry, the failed action is not affecting by your code

**Comment by canhuynh1998** [comment]
Thank you! Just making sure that I didn't do anything wrong along the way.

**Comment by sridhar-5** [comment]
Hello @ming-tsai long time,
I will review this in a few moments now.

**Comment by ming-tsai** [comment]
> Hello @ming-tsai long time,
> I will review this in a few moments now.

Yeah...

**Review by sridhar-5 — CHANGES_REQUESTED** [review]
your codebooks good to me @canhuynh1998. How ever there is a failing test. as per our organisations rules and regulations a pull request with failing tests cannot be merged. you can refer this https://github.com/actions/labeler/issues/16 to resolve your failing tests. for further help ping here.

**Comment by canhuynh1998** [comment]
@sridhar-5 thank you, for some reason, I cannot access the link you provided.

**Comment by sridhar-5** [comment]
> @sridhar-5 thank you, for some reason, I cannot access the link you provided.

can you try now? I've updates the comment.

**Comment by sridhar-5** [comment]
if your are still not able to access here is the link [https://github.com/actions/labeler/issues/16](url)

**Comment by canhuynh1998** [comment]
> > @sridhar-5 thank you, for some reason, I cannot access the link you provided.
> 
> can you try now? I've updated the comment. can you confirm if you are able to access?
Ok I got it right now. I will do it ASAP will let you know if I need any additional help

**Comment by canhuynh1998** [comment]
I just tried to fix it based on the provided link. Please take a look whenever you are convenient @sridhar-5

**Comment by Arsenic-ATG** [comment]
> your codebooks good to me @canhuynh1998. How ever there is a failing test. as per our organisations rules and regulations a pull request with failing tests cannot be merged. you can refer this [link](https://github.com/actions/labeler/issues/16) to resolve your failing tests. for further help ping here.

@sridhar-5 the failing labeler test has nothing to do with this PR, looks like the test is either not implemented properly or in process of begin implemented. 

Even @ming-tsai mentioned it above in the conversation here. : -

> > Can someone let me know what test did I fail? I am not really sure.
> 
> Don't worry, the failed action is not affecting by your code

**Review by sridhar-5 — APPROVED** [review]
Looks fine to Me @ming-tsai. If failing test isn't a problem. we can take this forward and merge this pull request.

Nice work @canhuynh1998.

**Pull request merged**
