### PR TITLE
chore(CPlusPlus): add find words matching pattern dictionary

### PR DESCRIPTION
**Pull request by yashh1234**
Given a dictionary of words where each word follows a CamelCase notation, find all words in it that matches a given pattern of all uppercase characters.

CamelCase Notation is the practice of writing compound words or phrases joined without spaces, where each word’s first letter is capitalized. For example, PowerPoint, LibreOffice, CinemaScope, etc., are in CamelCase.

We can use a Trie data structure to solve this problem. The idea is to insert all uppercase characters of each word in the CamelCase dictionary into a Trie. In contrast, the complete word is stored in a container associated with the corresponding leaf node. After the complete dictionary is processed, traverse the Trie and find all words that match the given pattern.

Output:
HiTech
HiTechLab
HiTechCity

**PR Checklist:**
- [x] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [x] My addition is on refer on the language README.md file
- [x] My addition does not have a spelling problem
- [x] My submission has a proper and user-friendly description of the algorithm
- [ ] My submission has the time complexity of the algorithm
- [x] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

### CODE REVIEW

**Comment by yashh1234** [comment]
@UG-SEP please review.

**Comment by yashh1234** [comment]
@ming-tsai i have edited the readme file. @Arsenic-ATG could you please review and merge this too.

**Comment by yashh1234** [comment]
@ming-tsai please assign review to @Arsenic-ATG

**Comment by Arsenic-ATG** [comment]
> @ming-tsai please assign review to @Arsenic-ATG

This also requires an update in readme.md [patch-1](https://github.com/yashh1234/DSA/tree/patch-1) branch this time.

**Comment by yashh1234** [comment]
Done @Arsenic-ATG

**Review by Arsenic-ATG — APPROVED** [review]

**Pull request merged**
