### PR TITLE
chore(Java): add shell sort

### PR DESCRIPTION
**Pull request by vasumanhas000**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

### CODE REVIEW

**Comment by vasumanhas000** [comment]
Added shell sort algorithm in java.

**Review by TawfikYasser — CHANGES_REQUESTED** [review]
Hi @vasumanhas000  and Welcome to **DSA**

Please remove unnecessary spaces in the code.

**Review by TawfikYasser — DISMISSED** [review]
LGTM 👏

**Comment by ming-tsai** [comment]
Hi @vasumanhas000,
Great Job!!! You are invited to be part of the team
> The invitation [link](https://github.com/MakeContributions)

**Pull request merged**
