### PR TITLE
chore(Python): add sum of n numbers using recursion

### PR DESCRIPTION
**Pull request by anika-kamath**
**PR Checklist:**
- [x] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [x] My addition is on refer on the language README.md file
- [x] My addition does not have a spelling problem
- [x] My submission has a proper and user-friendly description of the algorithm
- [x] My submission has the time complexity of the algorithm
- [x] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

### CODE REVIEW

**Review by Arsenic-ATG — CHANGES_REQUESTED** [review]
- Remove extra trailing indent from the program 
- Every addition of a new algorithm should be accompanied by an entry in the corresponding README.md file, please update that also.

**Comment by anika-kamath** [comment]
- extra trailing indent has been removed from code
- entry has been made in the README.md file

**Comment by Arsenic-ATG** [comment]
sorry for late review, 
but looks like the you have committed changes regarding updating the READMe.md on main branch of your fork ( while the current base of this pull request is [anika-branch](https://github.com/anika-kamath/DSA/tree/anika-branch) of your fork )
It's nothing a quick merge/rebase can't fix

**Comment by Arsenic-ATG** [comment]
> @Arsenic-ATG could you please help me out with this? I tried both merging and rebasing and it is showing me that the branch is up to date.

sure
if you are using git cli then 
1. on your local machine, navigate to the clone of your fork 
2. checkout anika-branch there (`$ git checkout anika-branch`)
3. rebase your fork's main branch onto anika-branch ( `$ git rebase main`)
4. push the the changes to remote to update your fork ( `$ git push origin anika-branch`)

Or, if you are using GitHub website interface then

1. go to [anika-branch](https://github.com/anika-kamath/DSA/tree/anika-branch) 
2. create a new pull request
3. change the *base* repository to `anika-khamant/DSA` and *base* branch to `anika-khamant`

Screenshot 2022-07-06 at 7 07 01 PM

4. change the *head* repository to also `anika-khamant/DSA` ( the interface will remove the option if the base and head repository is same )
5. change the *head* branch to `main`. 
6. create the pull request
7. choose `merge with rebase` instead of creating a merge commit

Screenshot 2022-07-06 at 7 08 25 PM

**Comment by anika-kamath** [comment]
@Arsenic-ATG Thank you very much. I have created a new pull request as I was getting an error via the CLI, but I cannot merge it directly as I require 1 approving review across the pull request. This is the new [pull request](https://github.com/MakeContributions/DSA/pull/773) which I created.

**Comment by Arsenic-ATG** [comment]
> @Arsenic-ATG Thank you very much. I have created a new pull request as I was getting an error via the CLI, but I cannot merge it directly as I require 1 approving review across the pull request. This is the new [pull request](https://github.com/MakeContributions/DSA/pull/773) which I created.

Looks like your forgot to change the base and head branch while creating one and created a pull request to Makecontribution's repository. 

The pull request was meant to be from your frok's main branch to your fork's anika-branch.

--

If you still face any problem while doing so then do let me know, I will try to fix it from my end end in that case 🙂

**Comment by anika-kamath** [comment]
Oh yes, I realised where I went wrong. Thank you very much, and extremely sorry for the inconvenience. 🙂

**Review by Arsenic-ATG — APPROVED** [review]

**Pull request merged**
