### PR TITLE
Algorithms Documentation [Java]

### PR DESCRIPTION
**Pull request by TawfikYasser**
Hi

Java Algorithms Documentation now here

I hope this be good.

Thanks

### CODE REVIEW

**Review by ming-tsai — COMMENTED** [review]
Nice, one question:
- Is it possible configure java github action?

**Comment by TawfikYasser** [comment]
> Nice, one question:
> 
> * Is it possible configure java github action?

Sorry I don't understand.

**Review by aayushjain7 — APPROVED** [review]
Nicee!! 💯

**Comment by TawfikYasser** [comment]
Please @aayushjain7 don't merge PR before @ming-tsai

**Comment by aayushjain7** [comment]
Noted.

**Comment by ming-tsai** [comment]
Ok, will check it about the build for Java

**Pull request merged**
