### PR TITLE
chore(CPlusPlus): add binary tree implementation

### PR DESCRIPTION
**Pull request by adarsh-kishore786**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [x] Other, please describe:

**Briefly describe the changes in this PR**

This program is an implementation of a binary tree in C++. It is templated and will work with all data types which are well ordered. It has the options of inserting a new element in tree, getting height of tree, printing the tree, searching for an element.

**Other information:**

### CODE REVIEW

**Review by aayushjain7 — CHANGES_REQUESTED** [review]
Update the readme.MD file also, for both the files.

**Comment by adarsh-kishore786** [comment]
Alright, the linked list one actually has still some issues, so I'll remove that one

**Review by aayushjain7 — APPROVED** [review]
LGTM!

**Comment by adarsh-kishore786** [comment]
Thanks :)

**Pull request merged**
