### PR TITLE
enh: jump search in C and C++

### LINKED ISSUE #258: Wanted to add jump search in c and cpp
### Hey @ming-tsai ,
I wanted to add **_jump search_** in c and cpp both languages 
Please assign me to do that 
Thanks

### PR DESCRIPTION
**Pull request by UG-SEP**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [x] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**
Added jump search in c language and modified jump search in c++

**Other information:**
closes #258 
Thanks

### CODE REVIEW

**Comment by ming-tsai** [comment]
Hi @UG-SEP,
Please check the codespell

**Comment by UG-SEP** [comment]
> Please check the codespell

corrected

**Comment by UG-SEP** [comment]
@ming-tsai  can you tell me the meaning of chore

**Comment by ming-tsai** [comment]
@UG-SEP this is the documentation talking about [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

**Review by aayushjain7 — APPROVED** [review]
Cool. Everything's goood! 💯

**Review by ming-tsai — APPROVED** [review]

**Pull request merged**
