### PR TITLE
chore(CPlusPlus): add 0/1 Knapsack problem to Dynamic Programming

### PR DESCRIPTION
**Pull request by ptarafdar001**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

### CODE REVIEW

**Comment by ptarafdar001** [comment]
Added a new algorithm (0/1 - Knapsack problem) in the Dynamic Programming section

**Comment by ptarafdar001** [comment]
how can I add this? can I close this pull request and send a new pull request with that message " chore(CPlusPlus): add 0/1 Knapsack problem to Dynamic Programming"

**Review by UG-SEP — CHANGES_REQUESTED** [review]
Please kindly do the given below changes as well as add your program name and link in CPP readme from [here](https://github.com/MakeContributions/DSA/blob/main/algorithms/CPlusPlus/README.md)
As well as correct the [ x] Algorithm-> [x] Algorithm

**Comment by ptarafdar001** [comment]
Okk ... I will do this.

Thanks & Regards
Prabir Tarafdar

**Review by ptarafdar001 — COMMENTED** [review]
I am done the following changes.

**Review by UG-SEP — CHANGES_REQUESTED** [review]
Everything is fine but you don't have to make changes in c++ [readme](https://github.com/MakeContributions/DSA/blob/main/algorithms/CPlusPlus/README.md)
as I told you to add your program name and link there at a proper topic (DP)

**Comment by ptarafdar001** [comment]
Now I have added the Program name and Link in the DP section and send another pull request.

**Comment by ptarafdar001** [comment]
Actually I have committed the actual cpp coding file "01-knapsack-bottom-up.cpp" from branch "add-prabir-dp"
And then I am updating the README.MD file with the path of the actual coding file, unfortunately this commit Is from another branch "patch-1" , can it abel to Marge?

**Comment by UG-SEP** [comment]
> Actually I have committed the actual cpp coding file "01-knapsack-bottom-up.cpp" from branch "add-prabir-dp"
> And then I am updating the README.MD file with the path of the actual coding file, unfortunately this commit Is from another branch "patch-1" , can it abel to Marge?

You just delete that branch and makes changes in this branch as you make changes in this branch GitHub will automate add the change in this branch
Hope you understand that what you have to do...

**Review by UG-SEP — APPROVED** [review]
Great job my bro @ptarafdar001
Thanks for contributing to this project if you have any doubt regarding Github you can ask [here](https://github.com/MakeContributions/DSA/discussions/383)
I hope you contribute more to this project 😊😊😊

**Pull request merged**
