### PR TITLE
added left-rotation.cpp file

### PR DESCRIPTION
**Pull request by Pavan-Kumar122**
Added a new file under Arrays section i.e. Left rotation using C++.

### CODE REVIEW

**Review by Arsenic-ATG — COMMENTED** [review]
kindly update the [index file](https://github.com/MakeContributions/DSA/blob/main/arrays/README.md) with the name of the file in there as discussed in [contribution guidelines](https://github.com/MakeContributions/DSA#contribution-guidelines)

**Comment by Pavan-Kumar122** [comment]
Done can you please check it.

**Comment by Pavan-Kumar122** [comment]
@Arsenic-ATG

**Review by Arsenic-ATG — DISMISSED** [review]

**Comment by Arsenic-ATG** [comment]
@Pavan-Kumar122 changes have been approved and most probably will soon be merged by @ming-tsai 

thanks for contributing 🙂

**Comment by ming-tsai** [comment]
Hi @Pavan-Kumar122,
Please solve the merge conflict

**Comment by Pavan-Kumar122** [comment]
I have resolved the conflict please check it. @ming-tsai

**Comment by ming-tsai** [comment]
Hi @Pavan-Kumar122,
Nice work, thanks for your contribution, and welcome to our team
> The invitation [link](https://github.com/MakeContributions)

**Review by ming-tsai — APPROVED** [review]

**Pull request merged**
