### PR TITLE
chore(Java): add square root algorithm

### PR DESCRIPTION
**Pull request by mohitchakraverty**
**PR Checklist:**
- [x] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [x] My addition is on refer on the language README.md file
- [x] My addition does not have a spelling problem
- [x] My submission has a proper and user-friendly description of the algorithm
- [x] My submission has the time complexity of the algorithm
- [x] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**
I have added a program to find square root of a number up to required decimal precision using Binary Search approach written in Java

**Other information:**

### CODE REVIEW

**Comment by mohitchakraverty** [comment]
@ming-tsai Waiting for your approval :)

**Comment by ming-tsai** [comment]
Hi @mohitchakraverty,
The file for binary search using SQRT is empty.
image

**Comment by ming-tsai** [comment]
Another question is if this is binary search, Why is this file inside the `Maths` folder?

**Comment by mohitchakraverty** [comment]
@ming-tsai I am unable to push my changes. I think there is some issue with the branch I am closing this pull request and creating a fresh one.

**Pull request closed without merging**
