### PR TITLE
chore(Python): add sankalp arrays

### PR DESCRIPTION
**Pull request by Sankalp7943**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**
Added 3 new coding problems which are standard for new coders.
1. Rotate Array: rotating an array based on an input k
2. Majority Element problem based on Boyer Moore Algorithm
3. Missing Element: based on basic question of sum of natural numbers

**Other information:**
Will be adding some more codes and new pull requests in recent upcoming days.

### CODE REVIEW

**Review by sridhar-5 — APPROVED** [review]
Great Work @Sankalp7943. I didn't find any flaws. Good to Go @ming-tsai.

**Comment by sridhar-5** [comment]
Appreciate the readabililty. Keep contributing @Sankalp7943.

Thanks
@sridhar-5

**Comment by ming-tsai** [comment]
Nice work

**Comment by ming-tsai** [comment]
Hi @sridhar-5,
Do not merge the pull request, thanks

**Comment by sridhar-5** [comment]
I'm so sorry @ming-tsai. Didn't know that. Will never do it again.

**Comment by ming-tsai** [comment]
Don't worry @sridhar-5

**Pull request merged**
