### PR TITLE
chore(C): add selection sort

### PR DESCRIPTION
**Pull request by Subathra19**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

### CODE REVIEW

**Review by Arsenic-ATG — CHANGES_REQUESTED** [review]
Program looks perfect

All that is left is to update the corresponding [readme.md](https://github.com/MakeContributions/DSA/blob/main/algorithms/C/README.md) file with your creation for indexing.

Just do that and the PR should be good to go.

**Comment by Subathra19** [comment]
> Program looks perfect
> 
> All that is left is to update the corresponding [readme.md](https://github.com/MakeContributions/DSA/blob/main/algorithms/C/README.md) file with your creation for indexing.
> 
> Just do that and the PR should be good to go.

I have done the required changes

**Comment by ming-tsai** [comment]
> > Program looks perfect
> > 
> > All that is left is to update the corresponding [readme.md](https://github.com/MakeContributions/DSA/blob/main/algorithms/C/README.md) file with your creation for indexing.
> > 
> > Just do that and the PR should be good to go.
> 
> I have done the required changes

Please modify this [file](https://www.github.com/Subathra19/DSA/tree/patch-1/algorithms%2FC%2FREADME.md)

**Comment by Arsenic-ATG** [comment]
Hi @Subathra19 , this pull request tracks the changes you did in a local branch of your fork ( [`Subathra19:patch-1`](https://github.com/Subathra19/DSA/tree/patch-1) ), so if you want to add something to this PR ( like addition to readme.md file ), just update your local branch with the required changes and GitHub will automatically update this PR with the required changes for you. 🙂

**Comment by Subathra19** [comment]
> > > Program looks perfect
> > > All that is left is to update the corresponding [readme.md](https://github.com/MakeContributions/DSA/blob/main/algorithms/C/README.md) file with your creation for indexing.
> > > Just do that and the PR should be good to go.
> > 
> > 
> > I have done the required changes
> 
> Please modify this [file](https://www.github.com/Subathra19/DSA/tree/patch-1/algorithms%2FC%2FREADME.md)

I have done the required modifications

**Comment by ming-tsai** [comment]
When you finish you have to click here to send the notification to review it again.
image

**Review by Arsenic-ATG — APPROVED** [review]

**Pull request merged**
