### PR TITLE
enh(CPlusPlus): add more comment on floyd warshall

### PR DESCRIPTION
**Pull request by Amarjeet2909**
**PR Checklist:**
- [x] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [x] My addition is on refer on the language README.md file
- [x] My addition does not have a spelling problem
- [x] My submission has a proper and user-friendly description of the algorithm
- [x] My submission has the time complexity of the algorithm
- [x] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [x] Optimization in previous algorithms
- [x] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

### CODE REVIEW

**Comment by Amarjeet2909** [comment]
@cclauss @brugner @pygaurav @khambley Pls review my commit

**Comment by cclauss** [comment]
Please remove my @mention above.  I am not a maintainer of this repository.

**Comment by Ashborn-SM** [comment]
you have a codespell fail
you might wanna fix that

**Comment by cclauss** [comment]
>  ./algorithms/CPlusPlus/Arrays/max-subarray-sum.cpp:23: Appraoch ==> Approach

**Comment by ming-tsai** [comment]
@Amarjeet2909 please update your branch with our main branch, I have already fix the issue

**Pull request closed without merging**
