### PR TITLE
docs: fix typo

### PR DESCRIPTION
**Pull request by LightMonarch**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [x] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**
Fix link to the **all-possible-insertion.cpp** in the README.md and Add **merge.cpp** to the README.md under **CPlusPlus** directory

**Other information:**

### CODE REVIEW

**Review by ming-tsai — APPROVED** [review]

**Comment by Ashborn-SM** [comment]
am i supposed to edit the README.md as well?

**Comment by ming-tsai** [comment]
I guess you didn't change the file's name, so some see the bug and rollback the change

**Comment by Ashborn-SM** [comment]
im sorry i commented in the wrong place

**Comment by ming-tsai** [comment]
If you are asking for [IdeaHub](https://github.com/MakeContributions/ideahub), you don't have to do it manually.

**Pull request merged**
