### PR TITLE
chore(CSharp): add Depth First Search

### PR DESCRIPTION
**Pull request by Waqar-107**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**
Added a new graph algorithm

**Other information:**

### CODE REVIEW

**Comment by ming-tsai** [comment]
Hi @Waqar-107,
If is possible please add the unit test?

**Comment by Waqar-107** [comment]
> Hi @Waqar-107,
> If is possible please add the unit test?

@ming-tsai I am not sure what tests to add. There can be multiple answers. Will a single answer do? Or do I have to write all possible outputs in the unit test?

**Comment by ming-tsai** [comment]
> > Hi @Waqar-107,
> > If is possible please add the unit test?
> 
> @ming-tsai I am not sure what tests to add. There can be multiple answers. Will a single answer do? Or do I have to write all possible outputs in the unit test?

@Waqar-107, take this as an [example](https://github.com/MakeContributions/DSA/blob/main/algorithms/CSharp/test/Sorts/bubble-sort.cs)

**Comment by ming-tsai** [comment]
Question: The DFS is not a tree DSA?

**Comment by Waqar-107** [comment]
> Question: The DFS is not a tree DSA?

Not necessarily. There can be cycles too. I will add the cycle detector too with the unit tests

**Comment by Waqar-107** [comment]
@ming-tsai I have added cycle detection and the unit tests.

**Review by ming-tsai — APPROVED** [review]

**Pull request merged**
