### PR TITLE
Add circular linked list java

### PR DESCRIPTION
**Pull request by toihirhalim**
changes made:  
- [x] source code for circular linked list.  
- [x] update readme to link to code.

### CODE REVIEW

**Review by TawfikYasser — APPROVED** [review]
LGTM 👍

**Comment by toihirhalim** [comment]
I just learned what LGTM stand for 
haha nice

**Comment by ming-tsai** [comment]
Nice work @toihirhalim

**Comment by toihirhalim** [comment]
Thanks @ming-tsai

**Pull request merged**
