### PR TITLE
Binary search add

### PR DESCRIPTION
**Pull request by Amisha-Mohapatra**

### CODE REVIEW

**Comment by Amisha-Mohapatra** [comment]
@paulsonjpaul  any suggestion what to fix?

**Comment by paulsonjpaul** [comment]
I have invited some contributors who are skilled in Java. Let's wait for their review.

**Review by sal81 — APPROVED** [review]

**Comment by Amisha-Mohapatra** [comment]
@paulsonjpaul it is approved by @sal81. Now is it ready to merge?

**Comment by paulsonjpaul** [comment]
I don't have access to merge the PR, @Amisha-Mohapatra. Please wait for @ming-tsai

**Review by ming-tsai — APPROVED** [review]
Hi @Amisha-Mohapatra,
Thanks for your contributions, and welcome to our team you could see invitation on our [home page](https://github.com/orgs/MakeContributions)

**Pull request merged**
