### PR TITLE
Add java code for linear search

### PR DESCRIPTION
**Pull request by sal81**
I have followed the general guidelines for contribution and left comments about the modifications required to run the code in terminal.

### CODE REVIEW

**Review by ming-tsai — APPROVED** [review]
Hi @sal81,
Thanks for your contribution, and welcome to our team

**Comment by sal81** [comment]
Thank you. Delighted to be a part of the team.

**Comment by ming-tsai** [comment]
@sal81, you could accept the invitation to [this page](https://github.com/MakeContributions)

**Comment by sal81** [comment]
Thanks, I have accepted the invitation.

**Pull request merged**
