### PR TITLE
chore(CSharp): adding binary-search

### PR DESCRIPTION
**Pull request by sonu-dev**
What kind of change does this PR introduce? (check at least one)

 

- [ ] Bugfix
- [x]  New algorithm
- [ ]  Optimization in previous algorithms
- [ ]  Code style update
- [ ]  Refactor
- [ ]  Documentation
- [ ]  Other, please describe:

**Briefly describe the changes in this PR**
Binary search in CSharp

Other information:

### CODE REVIEW

**Review by ming-tsai — CHANGES_REQUESTED** [review]
Hi @sonu-dev,
Nice work, but I would like to you make some couple of change:
- Please complete [the pull request](https://github.com/MakeContributions/DSA/blob/main/.github/PULL_REQUEST_TEMPLATE.md) template see #308 as an example
- Please rename the file's name according to [the contributions guidelines](https://github.com/MakeContributions/DSA/blob/main/README.md#contribution-guidelines), I know on C# we should use pascal case.
- Please ensure this code run on [.Net Fiddle](https://dotnetfiddle.net/Mobile), if not please look another file as an example
- Add it on [the readme index](https://github.com/sonu-dev/DSA/blob/add-new-file/algorithms/CSharp/README.md)

**Comment by sonu-dev** [comment]
> Hi @sonu-dev,
> Nice work, but I would like to you make some couple of change:
> 
> * Please complete [the pull request](https://github.com/MakeContributions/DSA/blob/main/.github/PULL_REQUEST_TEMPLATE.md) template see #308 as an example
> * Please rename the file's name according to [the contributions guidelines](https://github.com/MakeContributions/DSA/blob/main/README.md#contribution-guidelines), I know on C# we should use on pascal case.
> * Please ensure this code run on [.Net Fiddle](https://dotnetfiddle.net/Mobile), if not please look another file as an example
> * Add it on [the readme index](https://github.com/sonu-dev/DSA/blob/add-new-file/algorithms/CSharp/README.md)

**Comment by sonu-dev** [comment]
> > Hi @sonu-dev,
> > Nice work, but I would like to you make some couple of change:
> > 
> > * Please complete [the pull request](https://github.com/MakeContributions/DSA/blob/main/.github/PULL_REQUEST_TEMPLATE.md) template see #308 as an example
> > * Please rename the file's name according to [the contributions guidelines](https://github.com/MakeContributions/DSA/blob/main/README.md#contribution-guidelines), I know on C# we should use on pascal case.
> > * Please ensure this code run on [.Net Fiddle](https://dotnetfiddle.net/Mobile), if not please look another file as an example
> > * Add it on [the readme index](https://github.com/sonu-dev/DSA/blob/add-new-file/algorithms/CSharp/README.md)

Hi,

i have fixed the issues and re-open PR. Thanks

**Review by ming-tsai — APPROVED** [review]
Nice work @sonu-dev

**Pull request merged**
